// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package longrunningmicroflowupdates.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the LongRunningMicroflowUpdates module
	public static void aCT_StartLongRunningFlowOnScreen(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "LongRunningMicroflowUpdates.ACT_StartLongRunningFlowOnScreen", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_StartLongRunningFlowPopup(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "LongRunningMicroflowUpdates.ACT_StartLongRunningFlowPopup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void longRunningFlow(IContext context, longrunningmicroflowupdates.proxies.Job _job)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Job", _job == null ? null : _job.getMendixObject());
			Core.execute(context, "LongRunningMicroflowUpdates.LongRunningFlow", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_UpdateJobStatus(IContext context, longrunningmicroflowupdates.proxies.Job _job)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Job", _job == null ? null : _job.getMendixObject());
			Core.execute(context, "LongRunningMicroflowUpdates.SUB_UpdateJobStatus", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}